import { readFileSync } from 'node:fs'
import type { Logger } from '../log.js'
import { isRecord, listOf, mapOf, type State } from '../state/types.js'

/**
 * openGym's built-in exercises, shipped with leap in `data/exercises.json`:
 * the English text of openGym's `catalogue/` at a release (see NOTICE.md),
 * generated by `scripts/build-catalogue.mjs`. The pictures and animations are
 * never part of it.
 */
export const CATALOGUE_FILE = new URL('../../data/exercises.json', import.meta.url)

export interface Exercise {
  id: string
  name: string
  bodyPart?: string
  equipment?: string
  /** Main target muscle. */
  target?: string
  secondary: string[]
  /** English instruction steps (built-in exercises). */
  steps: string[]
  /** Built-in: strength, stretching, mobility, … */
  category?: string
  /** Built-in: one of the 1,324 exercises openGym had before 1.4.0 (ExerciseDB). */
  classic?: boolean
  custom: boolean
  /** Custom exercises: explicitly marked as an assistance machine (or explicitly not). */
  assisted?: boolean
  /** Custom exercises: the app's body-map muscles as stored, and the photo or video reference. */
  primaryMuscles?: string[]
  secondaryMuscles?: string[]
  media?: Record<string, unknown>
  /** What the exercise is (built-in and custom); the link is for custom exercises only. */
  description?: string
  url?: string
}

export interface BuiltinCatalog {
  exercises: Map<string, Exercise>
  /**
   * Ids that are a drawing of another exercise (a female figure of a male one): the app never
   * stores them, but a plan or an import can carry one, and it means the exercise it draws.
   */
  aliases?: Map<string, string>
  /** The openGym release the catalogue comes from. */
  source?: { version: string; commit: string }
  /** Why the built-in names are unavailable; tools then show ids. */
  error?: string
}

const text = (v: unknown): string | undefined => (typeof v === 'string' && v.trim() ? v.trim() : undefined)
const texts = (v: unknown): string[] => (Array.isArray(v) ? v.map(text).filter((s): s is string => s !== undefined) : [])

/** The shipped catalogue file (scripts/build-catalogue.mjs), reduced to what leap shows. */
export function parseCatalogue(data: unknown): BuiltinCatalog {
  if (!isRecord(data) || !Array.isArray(data.exercises)) throw new Error('the exercise catalogue has no exercise list')
  const exercises = new Map<string, Exercise>()
  for (const r of data.exercises) {
    if (!isRecord(r)) continue
    const id = text(r.id)
    const name = text(r.name)
    if (!id || !name) continue
    const e: Exercise = { id, name, secondary: texts(r.secondary), steps: texts(r.steps), custom: false }
    const bodyPart = text(r.bodyPart)
    const equipment = text(r.equipment)
    const target = text(r.target)
    const category = text(r.category)
    const description = text(r.description)
    if (bodyPart) e.bodyPart = bodyPart
    if (equipment) e.equipment = equipment
    if (target) e.target = target
    if (category) e.category = category
    if (description) e.description = description
    if (r.exercisedb === true) e.classic = true
    exercises.set(id, e)
  }
  const aliases = new Map<string, string>()
  for (const [alias, main] of Object.entries(mapOf(data, 'aliases'))) {
    if (typeof main === 'string' && exercises.has(main)) aliases.set(alias, main)
  }
  const source = mapOf(data, 'source')
  return { exercises, aliases, ...(typeof source.version === 'string' && typeof source.commit === 'string' ? { source: { version: source.version, commit: source.commit } } : {}) }
}

/** Reads the shipped catalogue once, on first use. */
export class BuiltinCatalogProvider {
  private loaded: BuiltinCatalog | undefined

  constructor(private readonly options: { file?: URL | string; log?: Logger } = {}) {}

  get(): Promise<BuiltinCatalog> {
    if (!this.loaded) {
      try {
        this.loaded = parseCatalogue(JSON.parse(readFileSync(this.options.file ?? CATALOGUE_FILE, 'utf8')))
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        this.options.log?.(`exercise catalogue unavailable: ${message}`)
        this.loaded = { exercises: new Map(), error: `built-in exercise names are unavailable (${message}); ids are shown instead` }
      }
    }
    return Promise.resolve(this.loaded)
  }
}

/** Whether `id` looks like a built-in exercise id (4 or 5 digits), for when the catalogue is unavailable. */
export const builtinIdShape = (id: string) => /^\d{4,5}$/.test(id)

/** The profile's own exercises, in the same shape as the built-in ones. */
export function customExercises(state: State | null): Exercise[] {
  const out: Exercise[] = []
  for (const c of listOf(state, 'customEx')) {
    const id = text(c.id)
    if (!id) continue
    const e: Exercise = {
      id,
      name: text(c.n) ?? id,
      secondary: texts(c.secondaries).length ? texts(c.secondaries) : texts(c.sm),
      steps: [],
      custom: true,
    }
    const bodyPart = text(c.bp)
    const equipment = text(c.eq)
    const target = text(c.tg) ?? texts(c.primaries)[0]
    const description = text(c.desc)
    const url = text(c.url)
    if (bodyPart) e.bodyPart = bodyPart
    if (equipment) e.equipment = equipment
    if (target) e.target = target
    if (description) e.description = description
    if (url) e.url = url
    if (typeof c.assisted === 'boolean') e.assisted = c.assisted
    if (texts(c.primaries).length) e.primaryMuscles = texts(c.primaries)
    if (texts(c.secondaries).length) e.secondaryMuscles = texts(c.secondaries)
    if (isRecord(c.media)) e.media = c.media
    out.push(e)
  }
  return out
}

/**
 * The catalogue's assistance machines by id (assisted dips, pull-ups and
 * chin-ups, assisted leg presses), so they are judged right even when the
 * catalogue file is unavailable. Verified against the shipped catalogue by a test.
 */
export const ASSISTED_IDS: ReadonlySet<string> = new Set(['0009', '0015', '0017', '0019', '0572', '1027', '1431', '1432', '2364', '2749'])

/**
 * Whether lighter is better (an assistance machine), as openGym decides it: an
 * explicit `assisted` flag wins; otherwise a leverage machine whose name says
 * "assist(ed)" (the assisted pull-up, dip and their variants). The dataset's
 * "assisted" equipment is partner-assisted stretches and the like, where
 * heavier is still harder, so it does not count.
 */
export function isAssisted(e: Exercise | undefined): boolean {
  if (!e) return false
  if (typeof e.assisted === 'boolean') return e.assisted
  return e.equipment === 'leverage machine' && /\bassist(ed)?\b/i.test(e.name)
}

/** Every exercise the profile can use: built-in ones and its own, by id. */
export class ExerciseIndex {
  readonly byId: Map<string, Exercise>
  readonly favourites: Set<string>
  private readonly notes: Record<string, unknown>
  private readonly aliases: Map<string, string>

  constructor(
    builtin: BuiltinCatalog,
    state: State | null,
    readonly warning: string | undefined = builtin.error,
  ) {
    this.byId = new Map(builtin.exercises)
    for (const c of customExercises(state)) this.byId.set(c.id, c)
    this.aliases = builtin.aliases ?? new Map()
    this.favourites = new Set(Array.isArray(state?.favEx) ? state.favEx.filter((x): x is string => typeof x === 'string') : [])
    this.notes = mapOf(state, 'exNotes')
  }

  /** The id an exercise is stored under: an alias id (a drawing of another exercise) means the exercise it draws. */
  canonical(id: string): string {
    return this.byId.has(id) ? id : (this.aliases.get(id) ?? id)
  }

  get(id: string): Exercise | undefined {
    return this.byId.get(this.canonical(id))
  }

  assisted(id: string): boolean {
    const e = this.get(id)
    return e ? isAssisted(e) : ASSISTED_IDS.has(id)
  }

  /** The exercise's name, or its id when it is unknown (deleted custom exercise, names unavailable). */
  name(id: string): string {
    return this.get(id)?.name ?? id
  }

  note(id: string): string | undefined {
    return text(this.notes[id])
  }
}
